rmdir /S /Q "Destination_test\"
ILRepack -target:library -lib:"C:\Program Files\Autodesk\Revit 2022" 
-out:"Destination_test\RevitAssemblyLoader.UITest\RevitAssemblyLoader.UITest.exe" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.UITest.exe" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\MaterialDesignColors.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\MaterialDesignThemes.Wpf.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\Microsoft.Bcl.AsyncInterfaces.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\Microsoft.Extensions.DependencyInjection.Abstractions.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\Microsoft.Extensions.DependencyInjection.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\Microsoft.Xaml.Behaviors.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.Abstractions.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.DI.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.MaterialDesignCut.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.Model.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\RevitAssemblyLoader.UI.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\System.Runtime.CompilerServices.Unsafe.dll" 
"RevitAssemblyLoader.UITest\bin\x64\Test\net48\System.Threading.Tasks.Extensions.dll"
pause
